{
 "title": "DetalhamentoIPMODELO",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "regional", "label": "Regional", "query": "${VAR_REGIONAL}" },
   { "name": "localidade", "label": "Localidade", "query": "${VAR_LOCALIDADE}" },
   { "name": "ip", "label": "IP", "query": "${VAR_IP}" },
   { "name": "uf", "label": "UF", "query": "${VAR_UF}" },
   { "name": "idponto", "label": "Id", "query": "${VAR_IDPONTO}" },
   {
    "name": "totaltx",
    "label": "TotalTx",
    "query": "select (sum(bytes)) as total from fluxomodelo where $__timeFilter(horario) and id_ponto = $idponto and sentido = 'tx' and indexrx ~ '^$instancia$' and origem = '$ip'"
   },
   {
    "name": "totalrx",
    "label": "TotalRx",
    "query": "select (sum(bytes)) as total from fluxomodelo where $__timeFilter(horario) and id_ponto = $idponto and sentido = 'rx' and indextx ~ '^$instancia$' and destino = '$ip'"
   },
   { "name": "instancia", "label": "Instancia", "query": "[0-9].*" },
   { "name": "circuito", "label": "Circuito", "query": "ACESSO" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<font color = #888888 size = 3><center><b>Cliente: MODELO&nbsp &nbsp &nbsp &nbsp${regional}</b></center></font>       \n<font color = #888888 size = 3><center><b>Localidade: ${localidade}&nbsp &nbsp &nbsp &nbspIP: ${ip}</b></center></font>       "
   },
   "targets": [
    {
     "rawSql": "SELECT\n  horario AS \"time\",\n  txbyte\nFROM recursoswan\nWHERE\n  $__timeFilter(horario)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Serviços TX",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select tag, (bytes/($totaltx+1))*100 as perc from (\n  select distinct tag, sum(bytes) over (partition by tag,sentido) as bytes from \n    fluxomodelo where \n        $__timeFilter(horario) \n    and id_ponto = '$idponto' \n    and indexrx ~ '^$instancia$' \n    and sentido = 'tx' \n    and origem = '$ip' order by bytes desc limit 10) t\n"
    }
   ]
  },
  {
   "title": "Serviços RX",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select tag, (bytes/($totalrx+1))*100 as perc from (\n  select distinct tag, sum(bytes) over (partition by tag,sentido) as bytes from \n    fluxomodelo where \n        $__timeFilter(horario) \n    and id_ponto = '$idponto' \n    and indextx ~ '^$instancia$' \n    and sentido = 'rx' \n    and destino = '$ip' order by bytes desc limit 10) t"
    }
   ]
  },
  {
   "title": "Mais Falantes Origem",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "select distinct t.destino as \"IP\", case when p.nome !~ 'MODELO' then '' else p.nome end as \"Localidade\", t.bytes as \"Bytes\"\nfrom (\n     select distinct f.destino, r.hostname, sum(f.bytes) as bytes\n       from fluxomodelo f\n       left join rede r on (r.ip::inet >> f.destino::inet and r.tipo = 'LAN')\n      where $__timeFilter(f.horario)\n        and f.id_ponto = '$idponto'\n        and f.sentido = 'tx'\n        and f.origem = '$ip'\n        and f.indexrx ~ '^$instancia$'\n        and f.indexrx != '0'\n      group by 1,2 order by 3 desc\n      limit 10\n) t\nleft join ponto p on (p.hostname = t.hostname)\norder by 3 desc\n\n"
    }
   ]
  },
  {
   "title": "Mais Falantes Destino",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "select distinct t.origem as \"IP\", case when p.nome !~ 'MODELO' then '' else p.nome end as \"Localidade\", t.bytes as \"Bytes\"\nfrom (\n     select distinct f.origem, r.hostname, sum(f.bytes) as bytes\n       from fluxomodelo f\n       left join rede r on (r.ip::inet >> f.origem::inet and r.tipo = 'LAN')\n      where $__timeFilter(f.horario)\n        and f.id_ponto = '$idponto'\n        and f.sentido = 'rx'\n        and f.destino = '$ip'\n        and f.indextx ~ '^$instancia$'\n        and f.indextx != '0'\n      group by 1,2 order by 3 desc\n      limit 10\n) t\nleft join ponto p on (p.hostname = t.hostname)\norder by 3 desc\n\n"
    }
   ]
  }
 ]
}