{
 "title": "DetalhamentoAplicacaoMODELO",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "localidade", "label": "Localidade", "query": "${VAR_LOCALIDADE}" },
   { "name": "idponto", "label": "Id", "query": "${VAR_IDPONTO}" },
   { "name": "servico", "label": "Servico", "query": "${VAR_SERVICO}" },
   { "name": "aplicacao", "label": "Aplicacao", "query": "${VAR_APLICACAO}" },
   { "name": "uf", "label": "UF", "query": "${VAR_UF}" },
   { "name": "circuito", "label": "Circuito", "query": "${VAR_CIRCUITO}" },
   { "name": "instancia", "label": "Instancia", "query": "${VAR_INSTANCIA}" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<font color = #888888 size = 3><center><b>Localidade: ${localidade}</b></center></font>\n<font color = #888888 size = 3><center><b>Serviço ${aplicacao}</b></center></font>       \n\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  horario AS \"time\",\n  txbyte\nFROM recursoswan\nWHERE\n  $__timeFilter(horario)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "IPs que Mais Transmitiram (Rede Interna)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "select origem as \"IP\", sum(bytes) as Bytes from fluxomodelo where \n        $__timeFilter(horario) \n    and id_ponto = $idponto \n    and sentido = 'tx' \n    and tag ='$servico' \n    and indexrx ~ '^$instancia$'\n    and indexrx != '0'\n    group by 1 order by 2 desc limit 5\n"
    }
   ]
  },
  {
   "title": "IPs que Mais Receberam (Rede interna)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "select destino as \"IP\", sum(bytes) as Bytes from fluxomodelo where \n        $__timeFilter(horario) \n    and id_ponto = $idponto \n    and sentido = 'rx'\n    and tag = '$servico'\n    and indextx ~ '^$instancia$'\n    and indextx != '0'\n    group by 1 order by 2 desc limit 5"
    }
   ]
  },
  {
   "title": "Servidores $aplicacao que Mais Transmitiram (Rede Externa)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "select distinct \n       t.destino as \"IP\"\n     , p.nome as \"Localidade\"\n     , t.bytes as \"Bytes\"\nfrom (\n     select distinct r.hostname, t.destino, t.bytes\n     from (\n          select distinct left(f.id_ponto::text,4)::int as id_cliente, f.destino, sum(f.bytes) as bytes\n            from fluxomodelo f\n           where $__timeFilter(f.horario)\n             and f.id_ponto = '$idponto'\n             and f.sentido = 'tx'\n             and f.tag ='$servico'\n             and f.indexrx ~ '^$instancia$'\n             and f.indexrx != '0'\n           group by 1,2 order by 3 desc\n           limit 10\n     ) t\n     left join rede r on (r.ip::inet >> t.destino::inet and left(r.id::text,4)::int = t.id_cliente and r.tipo = 'LAN')\n     order by 3 desc\n) t\nleft join ponto p on (p.hostname = t.hostname)\norder by 3 desc, 2\n/*\nselect destino as \"IP\", sum(bytes) as Bytes from fluxomodelo where \n        $__timeFilter(horario) \n    and id_ponto = $idponto \n    and sentido = 'tx' \n    and tag ='$servico' \n    and indexrx ~ '^$instancia$'\n    and indexrx != '0'\n    group by 1 order by 2 desc limit 5\n*/    "
    }
   ]
  },
  {
   "title": "Servidores $aplicacao que Mais Receberam (Rede Externa)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "select distinct \n       t.origem as \"IP\"\n     , p.nome as \"Localidade\"\n     , t.bytes as \"Bytes\"\nfrom (\n     select distinct r.hostname, t.origem, t.bytes\n     from (\n          select distinct left(f.id_ponto::text,4)::int as id_cliente, f.origem, sum(f.bytes) as bytes\n            from fluxomodelo f\n           where $__timeFilter(f.horario)\n             and f.id_ponto = '$idponto'\n             and f.sentido = 'rx'\n             and f.tag ='$servico'\n             and f.indextx ~ '^$instancia$'\n             and f.indextx != '0'\n           group by 1,2 order by 3 desc\n           limit 10\n     ) t\n     left join rede r on (r.ip::inet >> t.origem::inet and left(r.id::text,4)::int = t.id_cliente and r.tipo = 'LAN')\n     order by 3 desc\n) t\nleft join ponto p on (p.hostname = t.hostname)\norder by 3 desc, 2\n/*\nselect origem as \"IP\", sum(bytes) as Bytes from fluxomodelo where \n        $__timeFilter(horario) \n    and id_ponto = $idponto \n    and sentido = 'rx'\n    and tag = '$servico'\n    and indextx ~ '^$instancia$'\n    and indextx != '0'\n    group by 1 order by 2 desc limit 5\n*/    "
    }
   ]
  }
 ]
}