{
 "title": "InformacoesCircuitosRoteadoresMODELO",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "uf",
    "label": "UF",
    "query": "select uf from utilizacaoelipsemodelo where cliente ~* 'MODELO' order by uf"
   },
   {
    "name": "localidade",
    "label": "Localidade",
    "query": "select p.nome from ponto p, cliente c where substring(p.id::text,1,4) = c.id::text and c.sigla = 'MODELO' and substring(p.nome::text,1,2) = '$uf' order by 1;"
   },
   {
    "name": "zabbix",
    "label": "Zabbix",
    "query": "select p.hostname from  ponto p where  p.nome = '$localidade'"
   },
   {
    "name": "circuito",
    "label": "Circuito",
    "query": "select classe from rede where hostname ~* '$zabbix' and classe != 'LAN' and classe != 'WAN' and classe !~ 'TUNEL'  order by classe desc"
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": "select iface from rede where hostname ~* '$zabbix' and tipo = '$circuito' order by 1 desc"
   },
   {
    "name": "velocidade",
    "label": "Velocidade",
    "query": "select kbps from rede where hostname ~* '$zabbix' and tipo = '$circuito' and iface = '$interface' order by 1"
   },
   {
    "name": "data",
    "label": "data",
    "query": "SELECT CONCAT(to_char(to_timestamp(${__from} / 1000)::date, 'DD-MM-YYYY') , ' a ', to_char(to_timestamp(${__to} / 1000)::date, 'DD-MM-YYYY') )"
   },
   {
    "name": "proprietario",
    "label": "proprietario",
    "query": "select case when tipo = 'WANMAIS' then ' - Proprietário: MODELO'\n else ''\n end as tipo from\n  (select '$circuito'  as tipo )  t"
   },
   { "name": "link", "label": "link", "query": "${VAR_LINK}" }
  ]
 },
 "panels": [
  {
   "title": "Utilização do Circuito $circuito - $velocidade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.*(Entrada|Saída).*/",
        "$1"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "/WAN/MODELO/" },
     "host": { "filter": "/$zabbix/" },
     "item": {
      "filter": "/^Tráfego_.*(Entrada|Saída).*$interface .*$circuito.*/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/WAN/MODELO/" },
     "host": { "filter": "/$zabbix/" },
     "item": { "filter": "CPU - % Utilização" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Tempo de Resposta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.*(Tempo de Resposta).*/",
        "$1"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "/WAN/MODELO/" },
     "host": { "filter": "/$zabbix/" },
     "item": { "filter": "ICMP - Tempo de Resposta" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Memória",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/WAN/MODELO/" },
     "host": { "filter": "/$zabbix/" },
     "item": { "filter": "Memória - % Utilização" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Indicadores de Desempenho $proprietario",
   "type": "aidanmountford-html-panel",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 8 },
   "format": "short",
   "targets": [
    {
     "rawSql": "select concat(to_char(data,'dd-mm-yyyy'),';',cpu,';',mem,';',propagacao,';',e08,';',s08,';',e12,';',s12,';',e14,';',s14,';',erro_e,';',erro_s,';',descarte_e,';',descarte_s,';',desvio_ans) as \"DADOS\", data::timestamp as time from  indicadores_desempenho_gtic where hostname ~* '$zabbix' and interface = '$interface' and $__timeFilter(data) order by data;"
    }
   ]
  },
  {
   "title": "Erros / Descartes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.*(%(Descartes|Erros)_(Entrada|Saída)).*/",
        "$1"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "/WAN/MODELO/" },
     "host": { "filter": "/$zabbix/" },
     "item": {
      "filter": "/^%(Descart|Erros).*$interface .*$circuito/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}