{
 "title": "ResumoIndicadoresPortalMODELO",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "uf",
    "label": "UF",
    "query": "select distinct uf from utilizacaoelipsemodelo where cliente ~* 'MODELO' order by uf"
   },
   {
    "name": "localidade",
    "label": "Localidade",
    "query": "select p.nome from ponto p, cliente c where substring(p.id::text,1,4) = c.id::text and c.sigla = 'MODELO' and substring(p.nome::text,1,2) = '$uf' order by 1;"
   },
   {
    "name": "zabbix",
    "label": "Zabbix",
    "query": "select p.hostname from  ponto p where  p.nome = '$localidade'"
   },
   {
    "name": "idponto",
    "label": "IdPonto",
    "query": "select p.id from ponto p where p.hostname ~* '$zabbix'"
   },
   {
    "name": "circuito",
    "label": "Circuito",
    "query": "select distinct\n       case when temwanmais = 0 and temwan = 0 then 'ACESSO'\n            when temwanmais = 0 and temwan > 0 then tipo\n            else tipo\n        end as tipo\nfrom (\n     select distinct\n            tipo\n          , sum(contawanmais) over (partition by 0) as temwanmais\n          , sum(contawan) over (partition by 0) as temwan\n     from (\n          select tipo\n               , posicao\n               , case when tipo ~ 'WANMAIS'\n                      then 1\n                      else 0\n                  end as contawanmais\n               , case when tipo = 'WAN'\n                      then 1\n                      else 0\n                  end as contawan\n            from rede\n           where id::text ~ '^$idponto'\n     ) t\n) t;"
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": "select iface from rede where hostname ~* '$zabbix' and tipo = '$circuito' order by 1 desc"
   },
   {
    "name": "instancia",
    "label": "Instancia",
    "query": "select distinct  \n       case when temwanmais = 0 and (tipo = 'ACESSO') then '[0-9].*'\n            when temwanmais = 0 and temwan > 0   then '[0-9].*' \n            when temwanmais > 0 and tipo = 'LAN' then '[0-9].*' \n            when temwanmais > 0 and tipo != 'LAN' then posicao  \n       end as instancia \nfrom (\n     select tipo, posicao, iface, sum(contawanmais) over (partition by 0) as temwanmais, sum(contawan) over (partition by 0) as temwan \n     from (\n          select tipo\n                 , posicao\n                 , iface\n                 , case when tipo ~ 'WANMAIS' \n                        then 1 \n                        else 0 \n                 end as contawanmais\n                 , case when tipo = 'WAN' \n                        then 1 \n                        else 0 \n                 end as contawan  \n         from rede where id::text ~ '^$idponto' \n     ) t\n) t where tipo = '$circuito'  and iface = '$interface';\n"
   },
   {
    "name": "totaltx",
    "label": "totaltx",
    "query": "select (sum(bytes)) as total from fluxomodelo where $__timeFilter(horario) and id_ponto = $idponto and sentido = 'tx' and indexrx ~ '^$instancia$'"
   },
   {
    "name": "totalrx",
    "label": "totalrx",
    "query": "select (sum(bytes)) as total from fluxomodelo where $__timeFilter(horario) and id_ponto = $idponto and sentido = 'rx'  and indextx ~ '^$instancia$'"
   },
   {
    "name": "velocidade",
    "label": "Velocidade",
    "query": "select \n    case when kbps > 0 \n        then concat(kbps,' ','Kbps') \n        else null \n    end   from rede where \n              hostname ~* '$zabbix' \n      and tipo = '$circuito' order by 1 desc"
   }
  ]
 },
 "panels": [
  {
   "title": "Utilização do Circuito $circuito - $velocidade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.*(Entrada|Saída).*/",
        "$1"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "/WAN/MODELO/" },
     "host": { "filter": "/$zabbix/" },
     "item": {
      "filter": "/^Tráfego_.*(Entrada|Saída).*$interface .*$circuito.*/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/WAN/MODELO/" },
     "host": { "filter": "/$zabbix/" },
     "item": { "filter": "CPU - % Utilização" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Tempo de Resposta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.*(Tempo de Resposta).*/",
        "$1"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "/WAN/MODELO/" },
     "host": { "filter": "/$zabbix/" },
     "item": { "filter": "ICMP - Tempo de Resposta" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Memória",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/WAN/MODELO/" },
     "host": { "filter": "/$zabbix/" },
     "item": { "filter": "Memória - % Utilização" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Falantes Tx - LAN",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select origem as \"LAN\", sum(bytes) as Bytes from fluxomodelo where \n        $__timeFilter(horario) \n    and id_ponto = $idponto \n    and sentido = 'tx' \n    --and indextx = '$instancialan' \n    and indexrx ~ '^$instancia$'\n    and indexrx != '0'\n    group by 1 order by 2 desc limit 10"
    }
   ]
  },
  {
   "title": "Serviços TX",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select tag, (bytes/($totaltx+1))*100 as perc from (select distinct tag, sum(bytes) over (partition by tag,sentido) as bytes from fluxomodelo where $__timeFilter(horario) and id_ponto = '$idponto' and indexrx ~ '^$instancia$' and sentido = 'tx'  order by bytes desc limit 10) t"
    }
   ]
  },
  {
   "title": "Falantes Rx - LAN",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "select destino as \"LAN\", sum(bytes) as Bytes from fluxomodelo where \n        $__timeFilter(horario) \n    and id_ponto = $idponto \n    and sentido = 'rx' \n    and indextx ~ '^$instancia$'\n    and indextx != '0'\n    group by 1 order by 2 desc limit 10"
    }
   ]
  },
  {
   "title": "Serviços RX",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select tag, (bytes/($totalrx+1))*100 as perc from (select distinct tag, sum(bytes) over (partition by tag,sentido) as bytes from fluxomodelo where $__timeFilter(horario) and id_ponto = '$idponto' and indextx ~ '^$instancia$' and sentido = 'rx'  order by bytes desc limit 10) t"
    }
   ]
  }
 ]
}